Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      StorageType: gp2
      DBName: wordpress
      Engine: MySql
      MasterUsername: wordpress 
      MasterUserPassword: w0rdpr355
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-026dea5602e368e96
      InstanceType: t2.micro
  s3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wp-mr1try1